# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_post_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lead',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
