# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20160411_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 10, 13, 57, 29, 494652, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
