# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20160610_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
